package main

import (
	"github.com/dave/jennifer/jen"
	"github.com/jessevdk/go-flags"
	structview "github.com/reddec/struct-view"
	"log"
	"os"
	"path/filepath"
	"strings"
)

type Config struct {
	Package    string `short:"p" long:"package" env:"PACKAGE" description:"Package name (can be override by output dir)" default:"registry"`
	Output     string `short:"o" long:"output" env:"OUTPUT" description:"Generated output destination (- means STDOUT)" default:"-"`
	Type       string `short:"s" long:"struct" env:"STRUCT" description:"Struct name" required:"yes"`
	TypeName   string `short:"t" long:"type-name" env:"TYPE_NAME" description:"Typename for registry" default:"Registry"`
	Compressed bool   `short:"c" long:"compressed" env:"COMPRESSED" description:"Use GZIP compression for data"`
	Args       struct {
		Directories []string `help:"source directories (by default - current)"`
	} `positional-args:"yes"`
}

func main() {
	var config Config
	_, err := flags.Parse(&config)
	if err != nil {
		os.Exit(1)
	}
	if len(config.Args.Directories) == 0 {
		config.Args.Directories = []string{"."}
	}

	var out *jen.File
	if config.Output != "-" {
		pkg, err := structview.FindPackage(filepath.Dir(config.Output))
		if err != nil {
			// fallback
			log.Println(err)
			out = jen.NewFile(config.Package)
		} else if config.Package != "" {
			out = jen.NewFilePathName(pkg, config.Package)
		} else {
			out = jen.NewFilePathName(pkg, filepath.Base(pkg))
		}
	} else {
		out = jen.NewFile(config.Package)
	}
	ev := structview.BBoltStorage{
		Name:       config.Type,
		TypeName:   config.TypeName,
		Compressed: config.Compressed,
	}
	code, err := ev.Render(config.Args.Directories...)
	if err != nil {
		panic(err)
	}
	out.Add(code)
	var output = os.Stdout
	if config.Output != "-" {
		output, err = os.Create(config.Output)
		if err != nil {
			panic(err)
		}
		defer output.Close()
	}
	if config.Output != "" {
		for i, arg := range os.Args {
			if arg == config.Output {
				os.Args[i] = filepath.Base(arg)
				break
			}
		}
	}
	_, _ = output.WriteString("// Code generated by bbolt-storage. DO NOT EDIT.\n")
	_, _ = output.WriteString("//go:generate " + strings.Join(os.Args, " ") + "\n")
	err = out.Render(output)
	if err != nil {
		panic(err)
	}
}
