package main

import (
	"github.com/dave/jennifer/jen"
	"github.com/jessevdk/go-flags"
	"github.com/reddec/godetector"
	structview "github.com/reddec/struct-view"
	"os"
	"path/filepath"
	"strings"
)

type Config struct {
	Package      string `short:"p" long:"package" env:"PACKAGE" description:"Package name (can be override by output dir)" default:"enum"`
	Output       string `short:"o" long:"output" env:"OUTPUT" description:"Generated output destination (- means STDOUT)" default:"-"`
	TypeName     string `short:"t" long:"type-name" env:"TYPE_NAME" description:"Type name to wrap" required:"yes"`
	Name         string `long:"name" env:"NAME" description:"Result structure name" default:"RingBuffer"`
	Synchronized bool   `long:"synchronized" env:"SYNCHRONIZED" description:"Make collection be synchronized"`
	Import       string `short:"i" long:"import" env:"IMPORT" description:"Import for type"`
}

func main() {
	var config Config
	_, err := flags.Parse(&config)
	if err != nil {
		os.Exit(1)
	}

	var out *jen.File
	if config.Output != "-" {
		pkg := godetector.FindPackageNameByDir(filepath.Dir(config.Output))
		imp, err := godetector.FindImportPath(filepath.Dir(config.Output))
		if err != nil {
			out = jen.NewFile(pkg)
		} else {
			out = jen.NewFilePathName(imp, pkg)
		}
	} else {
		out = jen.NewFile(config.Package)
	}
	ev := structview.RingBuffer{
		Name:         config.Name,
		TypeName:     config.TypeName,
		Import:       config.Import,
		Synchronized: config.Synchronized,
	}
	code := ev.Generate()
	out.Add(code)
	var output = os.Stdout
	if config.Output != "-" {
		output, err = os.Create(config.Output)
		if err != nil {
			panic(err)
		}
		defer output.Close()
	}
	if config.Output != "" {
		for i, arg := range os.Args {
			if arg == config.Output {
				os.Args[i] = filepath.Base(arg)
				break
			}
		}
	}
	_, _ = output.WriteString("// Code generated by ring-buffer-gen. DO NOT EDIT.\n")
	_, _ = output.WriteString("//go:generate " + strings.Join(os.Args, " ") + "\n")
	err = out.Render(output)
	if err != nil {
		panic(err)
	}
}
