package main

import (
	"github.com/dave/jennifer/jen"
	"github.com/jessevdk/go-flags"
	structview "github.com/reddec/struct-view"
	"os"
	"path/filepath"
	"strings"
)

type Config struct {
	Package    string `short:"p" long:"package" env:"PACKAGE" description:"Package name (can be override by output dir)" default:"enum"`
	Output     string `short:"o" long:"output" env:"OUTPUT" description:"Generated output destination (- means STDOUT)" default:"-"`
	TypeName   string `short:"t" long:"type-name" env:"TYPE_NAME" description:"Enum name" default:"Manager"`
	SourceType string `short:"s" long:"source-type" env:"SOURCE_TYPE" description:"Source type name" default:"string"`
	Args       struct {
		Values []string `required:"yes"`
	} `positional-args:"values"`
}

func main() {
	var config Config
	_, err := flags.Parse(&config)
	if err != nil {
		os.Exit(1)
	}

	var out *jen.File
	if config.Output != "-" {
		pkg, err := structview.FindPackage(filepath.Dir(config.Output))
		if err != nil || config.Package != "" {
			// fallback
			out = jen.NewFile(config.Package)
		} else {
			out = jen.NewFilePathName(pkg, filepath.Base(pkg))
		}
	} else {
		out = jen.NewFile(config.Package)
	}
	ev := structview.EnumGen{
		TargetType: config.SourceType,
		Name:       config.TypeName,
		Values:     config.Args.Values,
	}
	code := ev.Generate()
	out.Add(code)
	var output = os.Stdout
	if config.Output != "-" {
		output, err = os.Create(config.Output)
		if err != nil {
			panic(err)
		}
		defer output.Close()
	}
	if config.Output != "" {
		for i, arg := range os.Args {
			if arg == config.Output {
				os.Args[i] = filepath.Base(arg)
				break
			}
		}
	}
	_, _ = output.WriteString("// Code generated by json-enum-gen. DO NOT EDIT.\n")
	_, _ = output.WriteString("//go:generate " + strings.Join(os.Args, " ") + "\n")
	err = out.Render(output)
	if err != nil {
		panic(err)
	}
}
