package main

import (
	"github.com/dave/jennifer/jen"
	"github.com/jessevdk/go-flags"
	"github.com/reddec/godetector"
	structview "github.com/reddec/struct-view"
	"log"
	"os"
	"path/filepath"
	"strings"
)

type Config struct {
	Package  string `short:"p" long:"package" env:"PACKAGE" description:"Package name (can be override by output dir)" default:""`
	Output   string `short:"o" long:"output" env:"OUTPUT" description:"Generated output destination (- means STDOUT)" default:"-"`
	Dir      string `long:"dir" env:"DIR" description:"Directory to scan" default:"."`
	TypeName string `short:"t" long:"type-name" env:"TYPE_NAME" description:"TypeName for cache" default:"Manager"`
	Gin      bool   `long:"gin" env:"GIN" description:"Enable binding for gin"`
}

func main() {
	var config Config
	_, err := flags.Parse(&config)
	if err != nil {
		os.Exit(1)
	}

	var out *jen.File
	if config.Output != "-" {
		pkg, err := godetector.FindImportPath(config.Output)
		if err != nil || config.Package != "" {
			// fallback
			out = jen.NewFile(config.Package)
		} else {
			out = jen.NewFilePathName(pkg, godetector.FindPackageNameByDir(filepath.Dir(config.Output)))
		}
	} else {
		out = jen.NewFile(config.Package)
	}
	ev := structview.ParamsGen{
		StructName: config.TypeName,
		Dir:        config.Dir,
		Gin:        config.Gin,
	}
	code, err := ev.Generate()
	if err != nil {
		log.Fatal(err)
	}
	out.Add(code)
	var output = os.Stdout
	if config.Output != "-" {
		output, err = os.Create(config.Output)
		if err != nil {
			panic(err)
		}
		defer output.Close()
	}
	if config.Output != "" {
		for i, arg := range os.Args {
			if arg == config.Output {
				os.Args[i] = filepath.Base(arg)
				break
			}
		}
	}
	_, _ = output.WriteString("// Code generated by params-gen. DO NOT EDIT.\n")
	_, _ = output.WriteString("//go:generate " + strings.Join(os.Args, " ") + "\n")
	err = out.Render(output)
	if err != nil {
		panic(err)
	}
}
